# Generated by Django 4.1.3 on 2023-01-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.watch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
