# Generated by Django 4.1.3 on 2023-01-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_servicing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicing',
            new_name='Service',
        ),
    ]
